COQPROJECTFILE?=_CoqProject

all: Makefile.rocq
	$(MAKE) -f Makefile.rocq $@

clean: $(COQPROJECTFILE)
	# We have to make the coq makefile in case it is missing
	rocq makefile -f $< -o Makefile.rocq
	$(MAKE) -f Makefile.rocq $@
	rm Makefile.rocq Makefile.rocq.conf

Makefile.rocq: $(COQPROJECTFILE)
	rocq makefile -f $< -o $@

.DEFAULT:
	$(MAKE) Makefile.rocq
	$(MAKE) -f Makefile.rocq $@

.PHONY: all clean
