---
fullname: Trocq
shortname: trocq
organization: coq-community
community: true
action: false
coqdoc: false
doi: 10.5281/zenodo.10492403

synopsis: >-
  A modular parametricity plugin for proof transfer in Coq

description: |-
  Trocq is a modular parametricity plugin for Coq. It can be used to
  achieve proof transfer by both translating a user goal into another,
  related, variant, and computing a proof that proves the corresponding implication.

  The plugin features a hierarchy of structures on relations, whose
  instances are computed from registered user-defined proof via
  parametricity. This hierarchy ranges from structure-less relations
  to an original formulation of type equivalence. The resulting
  framework generalizes [raw
  parametricity](https://arxiv.org/abs/1209.6336), [univalent
  parametricity](https://doi.org/10.1145/3429979) and
  [CoqEAL](https://github.com/coq-community/coqeal), and includes them
  in a unified framework.

  The plugin computes a parametricity translation "à la carte", by
  performing a fine-grained analysis of the requires properties for a
  given proof of relatedness. In particular, it is able to prove
  implications without resorting to full-blown type equivalence,
  allowing this way to perform proof transfer without necessarily
  pulling in the univalence axiom.

  The plugin is implemented in Coq-Elpi and the code of the
  parametricity translation is fairly close to a pen-and-paper
  sequent-style presentation.

publications:
- pub_url: https://hal.science/hal-04177913/document
  pub_title: 'Trocq: Proof Transfer for Free, With or Without Univalence'
- pub_url: https://hal.science/hal-04623207/document
  pub_title: 'Artifact Report: Trocq: Proof Transfer for Free, With or Without Univalence'
- pub_url: https://hal.science/hal-05192017/document
  pub_title: 'Trocq: Proof Transfer for Free, Beyond Equivalence and Univalence'

authors:
- name: Samy Avrillon 
  initial: false
- name: Cyril Cohen
  initial: true
- name: Enzo Crance
  initial: true
- name: Lucie Lahaye
  initial: false
- name: Assia Mahboubi
  initial: true

maintainers:
- name: Samy Avrillon 
  nickname: MysaaJava
- name: Cyril Cohen
  nickname: CohenCyril
- name: Enzo Crance
  nickname: ecranceMERCE
- name: Lucie Lahaye
  nickname: lweqx
- name: Assia Mahboubi
  nickname: amahboubi
- name: Tomas Vallejos
  nickname: Tvallejos

opam-file-maintainer: Enzo Crance <enzo.crance@inria.fr>

opam-file-version: dev

license:
  fullname: GNU Lesser General Public License v3.0
  identifier: LGPL-3.0-or-later
  file: LICENSE

supported_coq_versions:
  text: "9.0 and 9.1"
  opam: '{>= "9.0" & < "9.2"}'

make_target: "std"

install_flag: "-C std"

tested_coq_opam_versions:
- version: '9.0, 9.1'

dependencies:
- opam:
    name: coq-elpi
    version: '{>= "3.4.0"}'
  description: |-
    [Coq-Elpi](https://github.com/LPCIC/coq-elpi)

namespace: Trocq

keywords:
- name: automation
- name: elpi
- name: proof transfer
- name: isomorphism
- name: univalence
- name: parametricity

categories:
- name: Computer Science/Decision Procedures and Certified Algorithms/Decision procedures
- name: Miscellaneous/Coq Extensions

build: |-
  ## Building and installation instructions

  Trocq is still a prototype. It is not yet packaged in Opam or Nix.

  There are however three ways to experiment with it, all documented
  in the [INSTALL.md file](INSTALL.md).

documentation: |-
  ## Documentation

  See the [tutorial](https://rocq-community.org/trocq/index.html#/quick-start) for concrete use cases.
  
  In short, the plugin provides a tactic:
  - `trocq` (without arguments) which attempts to run a translation on
    a given goal, using the information provided by the user with the
    commands described below.
  - `trocq with R1 R2 ...` which works similarly to its argumentless counterpart
    except that it also uses translations associated to the relations `R1`,
    `R2`... ; see below regarding how to associated translations to a relation.
  - `trocq to A` which attempts to translate the goal to a new goal `A`.
  - `trocq to A with R1 R2` is a combination of the two options above
  
  And some commands:
  - `Trocq Use t` to use a translation `t` during the subsequent calls
    to the tactic `trocq`.
  - `Trocq Register Univalence u` to declare a univalence axiom `u`.
  - `Trocq Register Funext fe` to declare a function extensionality
    axiom `fe`.
  - `Trocq RelatedWith R t1 t2 ...` to associate `t1`, `t2`, ... to `R`.
    Subsequent calls to `trocq with R` will be able to use the translations `t1`,
    `t2`, ...
  - `Trocq Coercion "Off"|"On"` to enable or disable trocq being used as a fallback for Rocq's coercion.
  - `Trocq Logging "off"|"info"|"debug"|"trace"` to set the verbosity level.
  - `Trocq Usage` to print a small help message describing available trocq commands.
  - `Trocq Print Translations` to print a list of all currently registered Trocq translations.
  - `Trocq Print Translations G` prints the list of translations registered for a specific Gref `G`.
    it also prints all registered levels for each translation.
---
