(* ===========================================================================
   bs_p1.v -- monomorphic NatList and its base theorems
   ---------------------------------------------------------------------------
   Role       : Baby Step 1 - the source of truth every transfer starts from
   Depends on : (none)
   Provenance : authored for this study
   Measured   : 6 proofs, 19 tactic steps, 0 [Trocq Use]

   Effort convention: one period-terminated tactic = 1 step;
   [t1; t2.] = 1 step; bullet markers [- + * { }] = 0 steps;
   [Trocq Use] counted separately as commands.  Every count quoted in
   this file is generated by _count_steps.py, the single source of
   truth shared with _paper.tex and the figures -- regenerate it, do
   not hand-edit the numbers.
   =========================================================================== *)
From Stdlib Require Import ssreflect.
Local Open Scope nat_scope.

Set Universe Polymorphism.

Inductive NatList : Type :=
    | NNil  : NatList
    | NCons : nat -> NatList -> NatList.
Notation "x :n: l" := (NCons x l) (at level 60, right associativity).
Notation "[[]]"    := NNil.

Fixpoint nlength (l : NatList) : nat :=
    match l with
    | NNil       => O
    | NCons _ t  => S (nlength t)
    end.

Fixpoint napp (l1 l2 : NatList) : NatList :=
    match l1 with
    | NNil       => l2
    | NCons h t  => NCons h (napp t l2)
    end.
    
Example nlength_ex1 : nlength [[]] = O.
Proof. simpl. reflexivity. Qed.

Example nlength_ex2 : nlength (1 :n: 2 :n: 3 :n: [[]]) = 3.
Proof. simpl. reflexivity. Qed.

Example napp_ex : napp (1 :n: 2 :n: [[]]) (3 :n: 4 :n: [[]]) =
                       (1 :n: 2 :n: 3 :n: 4 :n: [[]]).
Proof. simpl. reflexivity. Qed.

Theorem nlength_napp : forall (l1 l2 : NatList),
    nlength (napp l1 l2) = nlength l1 + nlength l2.
Proof.
    intros l1 l2.
    induction l1 as [| h t IH]; simpl.
    - (* Base case: l1 = NNil. *)
      reflexivity.
    - (* Inductive step: l1 = NCons h t. *)
      rewrite IH. reflexivity.
Defined.

(* Import that solves [a + b = b + a] directly *)
From Stdlib Require Import Lia.

Theorem napp_length_comm : forall (l1 l2 : NatList),
    nlength (napp l1 l2) = nlength l2 + nlength l1.
Proof.
    intros l1 l2.
    rewrite nlength_napp.
    lia.
Defined.

Theorem napp_assoc : forall (l1 l2 l3 : NatList),
    napp (napp l1 l2) l3 = napp l1 (napp l2 l3).
Proof.
    intros l1 l2 l3.
    induction l1 as [| h t IH]; simpl.
    - (* Base case: l1 = NNil. *)
      reflexivity.
    - (* Inductive step: l1 = NCons h t. *)
      rewrite IH. reflexivity.
Defined.